const DEFAULT_TASK_NAME = 'New task'
const DEFAULT_TASK_COLOR = 'bg-sky-400'
const DEFAULT_TAG_NAME = 'New tag'
const DEFAULT_TAG_COLOR = 'bg-lime-400'

export { DEFAULT_TASK_COLOR, DEFAULT_TAG_NAME, DEFAULT_TASK_NAME, DEFAULT_TAG_COLOR }
